name: Production CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14
          cache: 'npm'

      - name: Install npm packages
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm ci

      - name: Test
        run: npm run test

