name: Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/firebase/functions

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "packages/firebase/functions/package-lock.json"

      - name: Cache Firebase emulators
        uses: actions/cache@v3
        with:
          path: ~/.cache/firebase/emulators/
          key: ${{ runner.os }}-firebase-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-firebase-

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Typescript prune
        run: npm run prune

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
